### ISSUE TITLE
IFRAME widgets

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-indices#6]
### Context:

Export graphs as a widget to embed in 3d parties. It would be nice to be able to share it as an image (freezed) or live with some controls (for instance change the time span).

### Current status:

I've added a quick demo for a tagcloud (rendering default time range on default sources for the "Cultural Heritage" topic): https://indices.weblyzard.com/embed-demo/tagcloud/cultural-heritage so that you can get a feeling of how an embeddable widget might work. Topic/Daterange/Sources can be made selectable via URL as well.

We're also currently working on making these embeddable visualisations available as Web Components (under-the-hood still rendered as an iframe).

Note: this link currently works for logged-in users only.

### TODO
- [x] Allow to export visualizations via iframes
- [ ] Do not require login to publish them in the indices platform.
- [ ] Provide a link to easy copy the embed code in the dashboard
