### ISSUE TITLE
Integrated Login between platforms

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-indices#7]
###  Context
The Dashboard should allow users to login/register via OAuth against the Decidim platform.

### Current status

Weblyzard panel seems capable of log in with other platforms. The main problem is that the login is generic through different clients in the Weblyzard, so the InDICEs instance needs to be personalized.

### TODO

- [ ] Configure Decidim as OAuth server (@platoniq)
- [ ] Allow InDICEs weblyzard dashboardl to have its own login page
- [ ] Configure Weblyzard to login against Indices
